version: 2

jobs:
  build:
    docker:

      - image: circleci/node:9.3
        environment:
          - PORT: 3000
          - PGUSER: 'test'
          - PGPASSWORD: 'test'
          - PGDATABASE: 'test'
          - PGHOST: 'localhost'
          - PGPORT: '5432'
    
      - image: circleci/postgres:10.1
        environment:
          - POSTGRES_USER: test
          - POSTGRES_DB: test
          - POSTGRES_PASSWORD: test

      - image: davidqhr/0x-testrpc:latest

    steps:
      - checkout

      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version

      - run:
          name: Change permissions from root to user
          command: sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}

      - run:
          name: Install NPM 6.1.0
          command: npm install npm@6.1.0 -g
          
      - run:
          name: Install Lerna
          command: npm install --global lerna

      - run:
          name: Install Package Dependencies 
          command: lerna bootstrap --stream

      - run:
          name: Build Packages
          command: CI=false lerna run build --stream

      - run:
          name: Test Packages
          command: lerna run test